### ISSUE TITLE
Alternative tool for container testing

### ISSUE THREAD

**Issue by tschifftner** [svrunit/svrunit#1]
Hey,

nice project. You might consider using https://github.com/GoogleContainerTools/container-structure-test as most tests are covered there already.

**Comment by boxblinkracer** [comment]
hi
thanks

yeah svrunit kinda exists since a very long time right now (maybe before the other), just had to release it because we are using it in another open source project :D
now im having fun improving it way more

**Comment by boxblinkracer** [comment]
omg but honestly...that looks a lot like this :D haha , i wasnt aware of that
